---
# vars file for cluster
access: <yourkey>
secret: <yoursecretkey>
image: ami-0bcf5425cdc1d8a85
sg: sg-007b77ccf46184ac6
key: mykey
region: ap-south-1
subnet: subnet-a4131acc
worker_count: 2
type: t2.micro

