---
# tasks file for myloadbalancer

- name: Install Load Balancer software 
  package: 
      name: "{{  package }}"
      state: present

- name: Starting the service  
  service: 
      name: "{{ service }}"
      state: started 

- name: Updating configuration file 
  template: 
      src: haproxy.cfg.j2 
      dest: /etc/haproxy/haproxy.cfg 
  notify: 
  - RESTART

- name: Configuring the Firewall
  firewalld:
      permanent: yes
      immediate: no
      port: 5000/tcp
      state: enabled
  ignore_errors: yes

