---
# tasks file for myapache

- name: Installing software 
  package: 
     name: "{{ item  }}"
     state: present
  loop: 
  - httpd
  - php  

- name: Starting service 
  service: 
     name: "{{ service }}"
     state: started 

- name: Copying Source 
  copy: 
     src: index.php
     dest: /var/www/html    
